USE ASW
GO

CREATE TABLE [AswSch].[AswMtoTraRcmModoFalla](
	[ClaUbicacion] [int] NOT NULL,
	[ClaEquipo] [int] NOT NULL,
	[ClaRcmFuncion] [int] NOT NULL,
	[ClaRcmFuncionFalla] [int] NOT NULL,
	[ClaRcmModoFalla] [int] NOT NULL,
	[DescRcmModoFalla] [varchar](400) NOT NULL,
	[FechaRegistro] [datetime] NOT NULL,
	[EsActivo] [int] NOT NULL,
	[ClaDepartamento] [int] NULL,
	[ClaArea] [int] NULL,
	[ClaRcmDecision] [int] NULL,
	[ClaTipoMantenimiento] [int] NULL,
	[ClaRcmFrecuencia] [int] NULL,
	[ClaRcmTipoModificacion] [int] NULL,
	[EfectoFalla] [varchar](max) NULL,
	[TareaPropuesta] [varchar](max) NULL,
	[EvalH] [int] NULL,
	[EvalS] [int] NULL,
	[EvalE] [int] NULL,
	[EvalO] [int] NULL,
	[Eval1] [int] NULL,
	[Eval2] [int] NULL,
	[Eval3] [int] NULL,
	[EvalH4] [int] NULL,
	[EvalH5] [int] NULL,
	[EvalS4] [int] NULL,
	[ModificacionPropuesta] [varchar](max) NULL,
	[ObservacionAuditoria] [varchar](max) NULL,
	[Tmef] [int] NULL,
	[FechaUltimaMod] [datetime] NOT NULL,
	[NombrePcMod] [varchar](64) NOT NULL,
	[ClaUsuarioMod] [int] NOT NULL,
	[ClaTipoDistribucion] [int] NULL,
	[Eta] [numeric](22, 4) NULL,
	[Beta] [numeric](22, 4) NULL,
	[Gamma] [numeric](22, 4) NULL,
	[FallaOculta] [tinyint] NULL,
	[TmefStd] [numeric](22, 4) NULL,
	[EsMigracion] [int] NULL,
	[Eta2] [numeric](22, 4) NULL,
	[Beta2] [numeric](22, 4) NULL,
	[Gamma2] [numeric](22, 4) NULL,
	[ClaveRcmModoFalla] [int] NULL,
	[EsCopiaGenerico] [int] NOT NULL,
	[ClaRcmModoFPadre] [int] NULL,
	[BajaLogica] [int] NULL,
	[FechaBajaLogica] [datetime] NULL,
	[EsGenericoPadre] [int] NULL,
 CONSTRAINT [PK_MtoTraRcmModoFalla] PRIMARY KEY CLUSTERED 
(
	[ClaUbicacion] ASC,
	[ClaEquipo] ASC,
	[ClaRcmFuncion] ASC,
	[ClaRcmFuncionFalla] ASC,
	[ClaRcmModoFalla] ASC
)

)