USE [master]
GO

/****** Object:  Database [ASW]    Script Date: 15/12/2022 03:03:05 p. m. ******/
CREATE DATABASE [ASW]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'ASW', FILENAME = N'D:\Data\ASW.mdf' , SIZE = 307200KB , MAXSIZE = UNLIMITED, FILEGROWTH = 512000KB ), 
 FILEGROUP [Bitacora] 
( NAME = N'Bitacora', FILENAME = N'D:\Data\Bitacora.ndf' , SIZE = 102400KB , MAXSIZE = UNLIMITED, FILEGROWTH = 102400KB )
 LOG ON 
( NAME = N'ASW_log', FILENAME = N'D:\Data\ASW_log.ldf' , SIZE = 102400KB , MAXSIZE = 2048GB , FILEGROWTH = 512000KB )
GO


USE [ASW]
GO
IF NOT EXISTS (SELECT name FROM sys.filegroups WHERE is_default=1 AND name = N'PRIMARY') ALTER DATABASE [ASW] MODIFY FILEGROUP [PRIMARY] DEFAULT
GO

