USE [master]
GO

/****** Object:  Database [sincroniza]    Script Date: 26/08/2020 10:21:46 a. m. ******/
CREATE DATABASE [sincroniza]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'sincroniza_Data', FILENAME = N'E:\Program Files\Microsoft SQL Server\MSSQL11.MSSQLSERVER\MSSQL\DATA\sincroniza_Data.MDF' , SIZE = 37056KB , MAXSIZE = UNLIMITED, FILEGROWTH = 10%)
 LOG ON 
( NAME = N'sincroniza_Log', FILENAME = N'E:\Program Files\Microsoft SQL Server\MSSQL11.MSSQLSERVER\MSSQL\DATA\sincroniza_Log.LDF' , SIZE = 7616KB , MAXSIZE = 2097152KB , FILEGROWTH = 10%)
GO

ALTER DATABASE [sincroniza] SET COMPATIBILITY_LEVEL = 90
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [sincroniza].[dbo].[sp_fulltext_database] @action = 'disable'
end
GO

ALTER DATABASE [sincroniza] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [sincroniza] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [sincroniza] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [sincroniza] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [sincroniza] SET ARITHABORT OFF 
GO

ALTER DATABASE [sincroniza] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [sincroniza] SET AUTO_CREATE_STATISTICS ON 
GO

ALTER DATABASE [sincroniza] SET AUTO_SHRINK ON 
GO

ALTER DATABASE [sincroniza] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [sincroniza] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [sincroniza] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [sincroniza] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [sincroniza] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [sincroniza] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [sincroniza] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [sincroniza] SET  DISABLE_BROKER 
GO

ALTER DATABASE [sincroniza] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [sincroniza] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [sincroniza] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [sincroniza] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [sincroniza] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [sincroniza] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [sincroniza] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [sincroniza] SET RECOVERY SIMPLE 
GO

ALTER DATABASE [sincroniza] SET  MULTI_USER 
GO

ALTER DATABASE [sincroniza] SET PAGE_VERIFY TORN_PAGE_DETECTION  
GO

ALTER DATABASE [sincroniza] SET DB_CHAINING OFF 
GO

ALTER DATABASE [sincroniza] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [sincroniza] SET TARGET_RECOVERY_TIME = 0 SECONDS 
GO

ALTER DATABASE [sincroniza] SET  READ_WRITE 
GO


