USE [master]
GO

/****** Object:  Database [TiCatalogo]    Script Date: 26/08/2020 12:48:42 p. m. ******/
CREATE DATABASE [TiCatalogo]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'TiCatalogo', FILENAME = N'E:\Program Files\Microsoft SQL Server\MSSQL11.MSSQLSERVER\MSSQL\DATA\TiCatalogo.mdf' , SIZE = 6503232KB , MAXSIZE = UNLIMITED, FILEGROWTH = 1024KB )
 LOG ON 
( NAME = N'TiCatalogo_log', FILENAME = N'E:\Program Files\Microsoft SQL Server\MSSQL11.MSSQLSERVER\MSSQL\DATA\TiCatalogo_1.ldf' , SIZE = 849408KB , MAXSIZE = 2048GB , FILEGROWTH = 10%)
GO

ALTER DATABASE [TiCatalogo] SET COMPATIBILITY_LEVEL = 100
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [TiCatalogo].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [TiCatalogo] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [TiCatalogo] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [TiCatalogo] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [TiCatalogo] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [TiCatalogo] SET ARITHABORT OFF 
GO

ALTER DATABASE [TiCatalogo] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [TiCatalogo] SET AUTO_CREATE_STATISTICS ON 
GO

ALTER DATABASE [TiCatalogo] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [TiCatalogo] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [TiCatalogo] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [TiCatalogo] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [TiCatalogo] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [TiCatalogo] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [TiCatalogo] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [TiCatalogo] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [TiCatalogo] SET  DISABLE_BROKER 
GO

ALTER DATABASE [TiCatalogo] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [TiCatalogo] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [TiCatalogo] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [TiCatalogo] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [TiCatalogo] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [TiCatalogo] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [TiCatalogo] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [TiCatalogo] SET RECOVERY FULL 
GO

ALTER DATABASE [TiCatalogo] SET  MULTI_USER 
GO

ALTER DATABASE [TiCatalogo] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [TiCatalogo] SET DB_CHAINING OFF 
GO

ALTER DATABASE [TiCatalogo] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [TiCatalogo] SET TARGET_RECOVERY_TIME = 0 SECONDS 
GO

ALTER DATABASE [TiCatalogo] SET  READ_WRITE 
GO


