INSERT [AswSch].[AswCatMensajeError] ([Idioma],[ErrorKey],[Mensaje])
VALUES('English','ORDER_NOT_EXIST','The production order was not found.')
INSERT [AswSch].[AswCatMensajeError] ([Idioma],[ErrorKey],[Mensaje])
VALUES('Spanish','ORDER_NOT_EXIST','La orden de produccion no existe.')
INSERT [AswSch].[AswCatMensajeError] ([Idioma],[ErrorKey],[Mensaje])
VALUES('English','ORDER_NOT_FROM_WORKCENTER','The production order for {{ClaveArticulos}} does not belong to {{ClaveWorkCenter}}.')
INSERT [AswSch].[AswCatMensajeError] ([Idioma],[ErrorKey],[Mensaje])
VALUES('Spanish','ORDER_NOT_FROM_WORKCENTER','La orden de produccion para el articulo {{ClaveArticulo}} no pertenece a {{ClaveWorkCenter}}.')
INSERT [AswSch].[AswCatMensajeError] ([Idioma],[ErrorKey],[Mensaje])
VALUES('English','ORDER_NOT_STARTABLE','The production order for {{ClaveArticulo}} is not in the right status to start it.')
INSERT [AswSch].[AswCatMensajeError] ([Idioma],[ErrorKey],[Mensaje])
VALUES('Spanish','ORDER_NOT_STARTABLE','La orden de produccion para el articulo {{ClaveArticulo}} no esta en el estatus correcto para iniciarla.')
INSERT [AswSch].[AswCatMensajeError] ([Idioma],[ErrorKey],[Mensaje])
VALUES('English','ORDER_NOT_FROM_CURRENT_PLAN','The production order for {{ClaveArticulo}} does not belong to a current production plan.')
INSERT [AswSch].[AswCatMensajeError] ([Idioma],[ErrorKey],[Mensaje])
VALUES('Spanish','ORDER_NOT_FROM_CURRENT_PLAN','La orden de produccion para el articulo {{ClaveArticulo}} no pertenece al plan de produccion actual.')
INSERT [AswSch].[AswCatMensajeError] ([Idioma],[ErrorKey],[Mensaje])
VALUES('Spanish','INCORRECT_PARAMETERS','Parametros incorrectos')
INSERT [AswSch].[AswCatMensajeError] ([Idioma],[ErrorKey],[Mensaje])
VALUES('English','INCORRECT_PARAMETERS','Incorrect parameters')
INSERT [AswSch].[AswCatMensajeError] ([Idioma],[ErrorKey],[Mensaje])
VALUES('English','NO_ACTIVE_ORDER','There is no active production order in the current production plan')
INSERT [AswSch].[AswCatMensajeError] ([Idioma],[ErrorKey],[Mensaje])
VALUES('Spanish','NO_ACTIVE_ORDER','No hay orden activa en el plan de produccion actual')
INSERT [AswSch].[AswCatMensajeError] ([Idioma],[ErrorKey],[Mensaje])
VALUES('English','MULTIPLE_ACTIVE_ORDERS','There are more than one active order')
INSERT [AswSch].[AswCatMensajeError] ([Idioma],[ErrorKey],[Mensaje])
VALUES('Spanish','MULTIPLE_ACTIVE_ORDERS','Hay más de una orden activa')
INSERT [AswSch].[AswCatMensajeError] ([Idioma],[ErrorKey],[Mensaje])
VALUES('English','UNASSOCIATED_RECORDS','Records not associated to the IdWorkCenter')
INSERT [AswSch].[AswCatMensajeError] ([Idioma],[ErrorKey],[Mensaje])
VALUES('Spanish','UNASSOCIATED_RECORDS','Registros no asociados al IdWorkCenter')
INSERT [AswSch].[AswCatMensajeError] ([Idioma],[ErrorKey],[Mensaje])
VALUES('English','AUTH_FAILED','Invalid username or password')
INSERT [AswSch].[AswCatMensajeError] ([Idioma],[ErrorKey],[Mensaje])
VALUES('Spanish','AUTH_FAILED','Usuario o contraseña invalido')
INSERT [AswSch].[AswCatMensajeError] ([Idioma],[ErrorKey],[Mensaje])
VALUES('English','INVALID_PROFILE','Invalid profile')
INSERT [AswSch].[AswCatMensajeError] ([Idioma],[ErrorKey],[Mensaje])
VALUES('Spanish','INVALID_PROFILE','Perfil invialido')
INSERT [AswSch].[AswCatMensajeError] ([Idioma],[ErrorKey],[Mensaje])
VALUES('English','APP_PROFILE_NOT_SET','Authorized profiles for app are not set')
INSERT [AswSch].[AswCatMensajeError] ([Idioma],[ErrorKey],[Mensaje])
VALUES('Spanish','APP_PROFILE_NOT_SET','Perfiles autorizados para la aplicacion sin configurar')
INSERT [AswSch].[AswCatMensajeError] ([Idioma],[ErrorKey],[Mensaje])
VALUES('English','INVALID_SHIFT','The selected shift {{TurnoExterno}} does not correspond to the current shift {{Turno}}')
INSERT [AswSch].[AswCatMensajeError] ([Idioma],[ErrorKey],[Mensaje])
VALUES('Spanish','INVALID_SHIFT','El turno seleccionado {{TurnoExterno}} no corresponde al turno actual {{Turno}}')