{
 "title": "Main dashboard",
 "time": { "from": "now/d+6h", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   {
    "name": "Cell",
    "label": "Location",
    "query": "EXEC [AswSch].[ASWCeldasAvisorCmb] 65,1"
   },
   { "name": "ClaUbicacion", "label": "ClaUbicacion", "query": "65" },
   { "name": "CurrentShift", "query": "EXEC [AswSch].[ASWTurnoActual]" }
  ]
 },
 "panels": [
  {
   "type": "stat",
   "gridPos": { "h": 2, "w": 3, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "rawSql": "EXEC  [AswSch].[ASW_CU305_Pag1_ObtenerNombreWorkCenter] $ClaUbicacion, '$Cell'"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 2, "w": 5, "x": 3, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "rawSql": "EXEC  [AswSch].[ASW_CU305_Pag1_ObtenerOrdenActual] $ClaUbicacion, '$Cell'"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 2, "w": 6, "x": 8, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "rawSql": "EXEC  [AswSch].[ASW_CU305_Pag1_ObtenerTurno] $ClaUbicacion, '${__from:date}', '${__to:date}', '$Cell', 1"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 2, "w": 6, "x": 14, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "EXEC  [AswSch].[ASW_CU305_Pag1_ObtenerCajas] $ClaUbicacion, '${__from:date}', '${__to:date}', '$Cell', 1\r\n"
    }
   ]
  },
  {
   "type": "williamvenner-timepickerbuttons-panel",
   "gridPos": { "h": 2, "w": 4, "x": 20, "y": 0 },
   "targets": [
    {
     "rawSql": "EXEC  [AswSch].[ASW_CU305_Pag1_ObtenerSelectorTurno] $ClaUbicacion, '${__to:date}', '$Cell', 1"
    }
   ]
  },
  {
   "title": "Shift OEE",
   "type": "gauge",
   "gridPos": { "h": 20, "w": 3, "x": 0, "y": 2 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "EXEC  [AswSch].[ASW_CU305_Pag1_ObtenerEGE] $ClaUbicacion, '${__to:date}', '$Cell', 1"
    }
   ]
  },
  {
   "title": "Status On/Off",
   "type": "state-timeline",
   "gridPos": { "h": 4, "w": 17, "x": 3, "y": 2 },
   "fieldConfig": { "defaults": { "unit": "string" } },
   "targets": [
    {
     "rawSql": "\r\nEXEC  [AswSch].[ASW_CU305_Pag1_ObtenerEstado] $ClaUbicacion, '${__from:date}', '${__to:date}', '$Cell', 1"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 20, "y": 2 },
   "fieldConfig": { "defaults": { "unit": "h" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "\r\n EXEC  [AswSch].[ASW_CU305_Pag1_ObtenerTiempo] $ClaUbicacion, '${__from:date}', '${__to:date}', '$Cell', 1\r\n"
    }
   ]
  },
  {
   "title": "Speed",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 17, "x": 3, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "rawSql": "EXEC  [AswSch].[ASW_CU305_Pag1_ObtenerVelocidad] $ClaUbicacion, '${__from:date}', '${__to:date}', '$Cell', 1\n"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 9, "w": 4, "x": 20, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "BPM" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "\r\n EXEC  [AswSch].[ASW_CU305_Pag1_ObtenerVelocidadMedia] $ClaUbicacion, '${__from:date}', '${__to:date}', '$Cell', 1\r\n"
    }
   ]
  },
  {
   "title": "Fulfillment",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 17, "x": 3, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "rawSql": "EXEC  [AswSch].[ASW_CU305_Pag1_ObtenerCumplimiento] $ClaUbicacion, '${__from:date}', '${__to:date}', '$Cell', 1"
    }
   ]
  },
  {
   "title": "Expected vs. Real ",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 20, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "dataset": "ASW",
     "rawSql": "EXEC  [AswSch].[ASW_CU305_Pag1_ObtenerRealExpectedProduction] $ClaUbicacion, '${__to:date}', '$Cell', 1"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 2, "w": 4, "x": 20, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "dataset": "ASW",
     "rawSql": "EXEC  [AswSch].[ASW_CU305_Pag1_ObtenerRealExpectedProduction] $ClaUbicacion, '${__to:date}', '$Cell', 1"
    }
   ]
  }
 ]
}