USE ASW
GO

DELETE [AswSch].[ASWCfgConfiguracion]

INSERT [AswSch].[ASWCfgConfiguracion] ([ClaUbicacion],[ClaConfiguracion],[ClaveConfiguracion],[DescConfiguracion],[DescConfiguracionES],[Valor1],[Valor2],[Valor3],[Svalor1],[Svalor2],[Svalor3],[Numero1],[Numero2],[Numero3],[Fecha1],[Fecha2],[Fecha3],[FechaUltimaMod],[NombrePcMod],[ClaUsuarioMod],[BajaLogica],[FechaBajaLogica])
VALUES(68,1,'UBI_DEFAULT','Default Location','Ubicacion Default',68,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,'Feb  1 2020 12:00:00:000AM','carga inicia',0,0,NULL)
INSERT [AswSch].[ASWCfgConfiguracion] ([ClaUbicacion],[ClaConfiguracion],[ClaveConfiguracion],[DescConfiguracion],[DescConfiguracionES],[Valor1],[Valor2],[Valor3],[Svalor1],[Svalor2],[Svalor3],[Numero1],[Numero2],[Numero3],[Fecha1],[Fecha2],[Fecha3],[FechaUltimaMod],[NombrePcMod],[ClaUsuarioMod],[BajaLogica],[FechaBajaLogica])
VALUES(68,2,NULL,'Order Sales Locations','Localidades Ordenes de Venta',NULL,NULL,NULL,'8,28','8-PB,28-WD / MO',NULL,NULL,NULL,NULL,NULL,NULL,NULL,'Feb  1 2020 12:00:00:000AM','carga inicia',0,0,NULL)
INSERT [AswSch].[ASWCfgConfiguracion] ([ClaUbicacion],[ClaConfiguracion],[ClaveConfiguracion],[DescConfiguracion],[DescConfiguracionES],[Valor1],[Valor2],[Valor3],[Svalor1],[Svalor2],[Svalor3],[Numero1],[Numero2],[Numero3],[Fecha1],[Fecha2],[Fecha3],[FechaUltimaMod],[NombrePcMod],[ClaUsuarioMod],[BajaLogica],[FechaBajaLogica])
VALUES(68,3,'MICROPARO','Micro-Torque Duration Minutes','Duracion MicroParo Minuto',3,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,'May 21 2020  3:29:08:970PM','carga inicia',0,0,NULL)
INSERT [AswSch].[ASWCfgConfiguracion] ([ClaUbicacion],[ClaConfiguracion],[ClaveConfiguracion],[DescConfiguracion],[DescConfiguracionES],[Valor1],[Valor2],[Valor3],[Svalor1],[Svalor2],[Svalor3],[Numero1],[Numero2],[Numero3],[Fecha1],[Fecha2],[Fecha3],[FechaUltimaMod],[NombrePcMod],[ClaUsuarioMod],[BajaLogica],[FechaBajaLogica])
VALUES(68,4,'CHANGEOVER','Duration ChangeOver Minutes','Duracion ChangeOver horas',30,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,'May 21 2020  3:32:18:647PM','carga inicia',0,0,NULL)
INSERT [AswSch].[ASWCfgConfiguracion] ([ClaUbicacion],[ClaConfiguracion],[ClaveConfiguracion],[DescConfiguracion],[DescConfiguracionES],[Valor1],[Valor2],[Valor3],[Svalor1],[Svalor2],[Svalor3],[Numero1],[Numero2],[Numero3],[Fecha1],[Fecha2],[Fecha3],[FechaUltimaMod],[NombrePcMod],[ClaUsuarioMod],[BajaLogica],[FechaBajaLogica])
VALUES(68,10,'CLA_NAILS_BOX','ClaCaracteristica nails/box','ClaCaracteristica clavos/caja',1412,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,'Jul 15 2020  1:49:44:523PM','Carga Inicial',0,0,NULL)
INSERT [AswSch].[ASWCfgConfiguracion] ([ClaUbicacion],[ClaConfiguracion],[ClaveConfiguracion],[DescConfiguracion],[DescConfiguracionES],[Valor1],[Valor2],[Valor3],[Svalor1],[Svalor2],[Svalor3],[Numero1],[Numero2],[Numero3],[Fecha1],[Fecha2],[Fecha3],[FechaUltimaMod],[NombrePcMod],[ClaUsuarioMod],[BajaLogica],[FechaBajaLogica])
VALUES(68,11,'SCRAP_LIMIT','Scrap Limmit','Limite Scrap',5,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,'Jul 15 2020  1:49:44:523PM','Carga Inicial',0,0,NULL)
INSERT [AswSch].[ASWCfgConfiguracion] ([ClaUbicacion],[ClaConfiguracion],[ClaveConfiguracion],[DescConfiguracion],[DescConfiguracionES],[Valor1],[Valor2],[Valor3],[Svalor1],[Svalor2],[Svalor3],[Numero1],[Numero2],[Numero3],[Fecha1],[Fecha2],[Fecha3],[FechaUltimaMod],[NombrePcMod],[ClaUsuarioMod],[BajaLogica],[FechaBajaLogica])
VALUES(68,12,NULL,'ruta archivos operadores','ruta archivos operadores',NULL,NULL,NULL,'\\localhost\ASW\operadores',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,'2020-09-04 13:33:00','Carga Inicial',0,0,NULL)
INSERT [AswSch].[ASWCfgConfiguracion] ([ClaUbicacion],[ClaConfiguracion],[ClaveConfiguracion],[DescConfiguracion],[DescConfiguracionES],[Valor1],[Valor2],[Valor3],[Svalor1],[Svalor2],[Svalor3],[Numero1],[Numero2],[Numero3],[Fecha1],[Fecha2],[Fecha3],[FechaUltimaMod],[NombrePcMod],[ClaUsuarioMod],[BajaLogica],[FechaBajaLogica])
VALUES(68,13,'PATH_BLUEPRINT','Path to blueprint folder in the tablet','Ruta de carpeta de blueprints en la tablet',NULL,NULL,NULL,'../../Proyecto/Contents/blueprints/',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,'2020-10-14 13:33:00','Carga Inicial',0,0,NULL)
INSERT [AswSch].[ASWCfgConfiguracion] ([ClaUbicacion],[ClaConfiguracion],[ClaveConfiguracion],[DescConfiguracion],[DescConfiguracionES],[Valor1],[Valor2],[Valor3],[Svalor1],[Svalor2],[Svalor3],[Numero1],[Numero2],[Numero3],[Fecha1],[Fecha2],[Fecha3],[FechaUltimaMod],[NombrePcMod],[ClaUsuarioMod],[BajaLogica],[FechaBajaLogica])
VALUES(68,14,'AUTOLOGIN','Autologin configuration','Configuracion de autologin',1,3502001,NULL,'COLLATOR',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,'2022-04-25 13:33:00','Carga Inicial',0,0,NULL)
INSERT [AswSch].[ASWCfgConfiguracion] ([ClaUbicacion],[ClaConfiguracion],[ClaveConfiguracion],[DescConfiguracion],[DescConfiguracionES],[Valor1],[Valor2],[Valor3],[Svalor1],[Svalor2],[Svalor3],[Numero1],[Numero2],[Numero3],[Fecha1],[Fecha2],[Fecha3],[FechaUltimaMod],[NombrePcMod],[ClaUsuarioMod],[BajaLogica],[FechaBajaLogica])
VALUES(68,15,'ERROR_MAILS','Error Mail List','Correos Reportes de Error',NULL,NULL,NULL,'ngalaz@deacero.com;josari@deacero.com;mrodriguezc@deacero.com',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,'2022-06-15 11:34:03.657','Carga Inicial',0,0,NULL)
INSERT [AswSch].[ASWCfgConfiguracion] ([ClaUbicacion],[ClaConfiguracion],[ClaveConfiguracion],[DescConfiguracion],[DescConfiguracionES],[Valor1],[Valor2],[Valor3],[Svalor1],[Svalor2],[Svalor3],[Numero1],[Numero2],[Numero3],[Fecha1],[Fecha2],[Fecha3],[FechaUltimaMod],[NombrePcMod],[ClaUsuarioMod],[BajaLogica],[FechaBajaLogica])
VALUES(68,16,'TEST_MAIL','Test Error Mail List','Test Error Mail List',NULL,NULL,NULL,'josari@deacero.com',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,'2022-06-15 11:34:03.657','Carga Inicial',0,0,NULL)
INSERT [AswSch].[ASWCfgConfiguracion] ([ClaUbicacion],[ClaConfiguracion],[ClaveConfiguracion],[DescConfiguracion],[DescConfiguracionES],[Valor1],[Valor2],[Valor3],[Svalor1],[Svalor2],[Svalor3],[Numero1],[Numero2],[Numero3],[Fecha1],[Fecha2],[Fecha3],[FechaUltimaMod],[NombrePcMod],[ClaUsuarioMod],[BajaLogica],[FechaBajaLogica])
VALUES(68,17,'CARGA_ARTICULO','Carga inicial de Articulos por orden de producción (1) o capacidad (2) según la ubicación','Carga inicial de Articulos por orden de producción (1) o capacidad (2) según la ubicación',1,NULL,NULL,'NULL',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,'2023-01-24 17:00:00.000','Carga Inicial',0,0,NULL)

	

