USE ASW
GO

select * from  [AswSch].[AswBitAndon]
select * from  [AswSch].[AswBitBitacoraBajaEficiencia]
select * from  [AswSch].[AswBitBitacoraParo]
select * from  [AswSch].[AswBitBitacoraProduccion]
select * from  [AswSch].[AswBitGestionDeProduccion_PAL]
select * from  [AswSch].[AswEstCumplimientoDiario]
select * from  [AswSch].[AswEstCumplimientoMensual]
select * from  [AswSch].[AswEstCumplimientoSemanal]
select * from  [AswSch].[AswEstEGEDiario]
select * from  [AswSch].[AswEstEGESemanal]
select * from  [AswSch].[AswEstEGEMensual]
select * from  [AswSch].[AswMtoTraOT]
select * from  [AswSch].[AswMtoTraOTActividad]
select * from  [AswSch].[AswMtoTraOTActividadDerivada]
select * from  [AswSch].[AswMtoTraOTActividadVariable]
--select * from  [AswSch].[AswMtoTraRcmModoFalla]
--select * from  [AswSch].[AswRelMtoSubAreaCelda]
select * from  [AswSch].[AswTraFinCajaMCSW]
select * from  [AswSch].[AswTraMateriaPrima]
select * from  [AswSch].[ASWTraOrdenProduccion]
select * from  [AswSch].[ASWTraOrdenProduccionDet]

delete [AswSch].[AswBitAndon]
delete [AswSch].[AswBitBitacoraBajaEficiencia]
delete [AswSch].[AswBitBitacoraParo]
delete [AswSch].[AswBitBitacoraProduccion]
delete [AswSch].[AswBitGestionDeProduccion_PAL]
delete [AswSch].[AswEstCumplimientoDiario]
delete [AswSch].[AswEstCumplimientoMensual]
delete [AswSch].[AswEstCumplimientoSemanal]
delete [AswSch].[AswEstEGEDiario]
delete [AswSch].[AswEstEGESemanal]
delete [AswSch].[AswEstEGEMensual]
delete [AswSch].[AswMtoTraOT]
delete [AswSch].[AswMtoTraOTActividad]
delete [AswSch].[AswMtoTraOTActividadDerivada]
delete [AswSch].[AswMtoTraOTActividadVariable]
--delete [AswSch].[AswMtoTraRcmModoFalla]
--delete [AswSch].[AswRelMtoSubAreaCelda]
delete [AswSch].[AswTraFinCajaMCSW]
delete [AswSch].[AswTraMateriaPrima]
delete [AswSch].[ASWTraOrdenProduccion]
delete [AswSch].[ASWTraOrdenProduccionDet]